# Generated by Django 3.1.2 on 2020-10-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
    ]
