# Generated by Django 3.1.2 on 2020-10-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20201004_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Foto'),
        ),
    ]
