# Generated by Django 3.1.2 on 2020-10-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20201004_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Foto'),
        ),
    ]
