# Generated by Django 3.1.2 on 2020-10-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20200726_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='anho',
            new_name='año',
        ),
    ]
