# Generated by Django 3.1.2 on 2020-10-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_auto_20201002_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['id', 'nombres', 'apellidos', 'sexo', 'descripcion', 'carrera'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['id', 'nombre', 'nombre_corto', 'facultad', 'año'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='deporte',
            options={'ordering': ['id', 'alumno', 'masculino', 'femenino']},
        ),
        migrations.AlterModelOptions(
            name='deportefemenino',
            options={'ordering': ['id', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='deportemasculino',
            options={'ordering': ['id', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='facultad',
            options={'ordering': ['id', 'universidad', 'nombre', 'nombre_corto', 'especialidad'], 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.AlterModelOptions(
            name='universidad',
            options={'ordering': ['id', 'nombre', 'nombre_corto'], 'verbose_name': 'Universidad', 'verbose_name_plural': 'Universidades'},
        ),
    ]
